/**
 * OpenClaw Skill: Shopping Agent
 * Generates final optimized shopping list, posts to Discord, sends to Telegram.
 * Commands: /shopping list | /shopping send | /shopping optimize [budget]
 */

import Database from "better-sqlite3";
import path from "path";

const DB_PATH = path.join(process.env.OPENCLAW_WORKSPACE_DIR || "/data/workspace", "pantry.db");
const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;

function getDb() {
  const db = new Database(DB_PATH);
  return db;
}

function getCurrentWeek() {
  const now = new Date();
  const start = new Date(now);
  start.setDate(now.getDate() - now.getDay() + 1);
  return start.toISOString().split("T")[0];
}

async function sendTelegram(message) {
  if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) {
    return { ok: false, error: "TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set in Railway env vars" };
  }
  const res = await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: TELEGRAM_CHAT_ID,
      text: message,
      parse_mode: "Markdown"
    })
  });
  return res.json();
}

function getBestPrices(db, items) {
  const result = [];
  for (const item of items) {
    const row = db.prepare(`
      SELECT store, price, unit FROM prices 
      WHERE item = ? ORDER BY price ASC LIMIT 1
    `).get(item.toLowerCase());
    result.push({ item, store: row?.store || "any", price: row?.price || null, unit: row?.unit || "" });
  }
  return result;
}

export const skill = {
  name: "shopping-agent",
  description: "Generate and send optimized shopping lists via Telegram.",
  commands: [
    {
      name: "shopping",
      description: "Shopping list management and delivery",
      async run({ args, reply }) {
        const db = getDb();
        const [action] = args;

        if (!action || action === "list") {
          const week = getCurrentWeek();
          const row = db.prepare("SELECT plan_json FROM meal_plans WHERE week = ?").get(week);
          if (!row) return reply("No meal plan found. Run `/meals plan` first.");

          const plan = JSON.parse(row.plan_json);
          const items = getBestPrices(db, plan.shoppingList || []);

          const lines = ["🛒 **Shopping List — Week of " + week + "**\n"];
          let totalEstimate = 0;

          // Group by store
          const byStore = {};
          for (const item of items) {
            if (!byStore[item.store]) byStore[item.store] = [];
            byStore[item.store].push(item);
            if (item.price) totalEstimate += item.price;
          }

          for (const [store, storeItems] of Object.entries(byStore)) {
            lines.push(`\n🏪 **${store}**`);
            for (const i of storeItems) {
              const priceStr = i.price ? ` — €${i.price.toFixed(2)}` : "";
              lines.push(`  • ${i.item}${priceStr}`);
            }
          }

          if (totalEstimate > 0) {
            lines.push(`\n💰 **Estimated total: €${totalEstimate.toFixed(2)}**`);
          }

          return reply(lines.join("\n"));
        }

        if (action === "send") {
          const week = getCurrentWeek();
          const row = db.prepare("SELECT plan_json FROM meal_plans WHERE week = ?").get(week);
          if (!row) return reply("No meal plan found. Run `/meals plan` first.");

          const plan = JSON.parse(row.plan_json);
          const items = getBestPrices(db, plan.shoppingList || []);

          // Build Telegram message
          const tgLines = [
            `🛒 *Shopping List — ${week}*`,
            ``,
            ...items.map(i => {
              const price = i.price ? ` (€${i.price.toFixed(2)} @ ${i.store})` : "";
              return `• ${i.item}${price}`;
            }),
            ``,
            `_Generated by your Family Meal Planner 🦞_`
          ];

          const tgMessage = tgLines.join("\n");
          const result = await sendTelegram(tgMessage);

          if (result.ok) {
            return reply(`✅ Shopping list sent to Telegram! (${items.length} items)`);
          } else {
            return reply(`❌ Telegram send failed: ${result.error || result.description}\n\nMake sure \`TELEGRAM_BOT_TOKEN\` and \`TELEGRAM_CHAT_ID\` are set in Railway.`);
          }
        }

        if (action === "optimize") {
          const budget = parseFloat(args[1]) || 80;
          const week = getCurrentWeek();
          const row = db.prepare("SELECT plan_json FROM meal_plans WHERE week = ?").get(week);
          if (!row) return reply("No meal plan found. Run `/meals plan` first.");

          const plan = JSON.parse(row.plan_json);
          const items = getBestPrices(db, plan.shoppingList || []);
          const withPrices = items.filter(i => i.price !== null);
          const total = withPrices.reduce((sum, i) => sum + i.price, 0);

          if (total <= budget) {
            return reply(`✅ Shopping list fits within €${budget} budget. Estimated: €${total.toFixed(2)}`);
          }

          // Simple optimization: flag most expensive items
          const sorted = [...withPrices].sort((a, b) => b.price - a.price);
          const expensive = sorted.slice(0, 3);
          const lines = [
            `⚠️ Estimated €${total.toFixed(2)} exceeds budget of €${budget}`,
            ``,
            `💡 **Consider substituting:**`,
            ...expensive.map(i => `• **${i.item}** (€${i.price.toFixed(2)}) — find cheaper alternative or skip`),
          ];
          return reply(lines.join("\n"));
        }

        return reply("Usage: `/shopping list` | `/shopping send` | `/shopping optimize [budget]`");
      }
    }
  ]
};
